PartidoPolitico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.urls import path
from django.urls.conf import include
from django.urls.resolvers import URLPattern
from .import views


app_name = 'app'
urlpatterns = [
    path('',views.index, name= 'index'),
    path('CambiarDatosCuentaP',views.CambiarDatosCuentaP_view, name='CambiarDatosCuentaP'),
    path('CambioExitosoP', views.CambioExitosoP_view, name='CambioExitosoP'),
    path('CrearPartidoPoliticoP', views.CrearPartidoPoliticoP_view, name='CrearPartidoPoliticoP'),
<<<<<<< HEAD
=======
    path('ConsultarListaPartidosPoliticosAP', views.ConsultarListaPartidosPoliticosAP_view, name='ConsultarListaPartidosPoliticosAP'),
    path('ConsultarListaPartidosPoliticosCP', views.ConsultarListaPartidosPoliticosCP_view, name='ConsultarListaPartidosPoliticosCP'),
>>>>>>> 5176e908c0717b738d61ee472146b667e7d5d412
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.http import HttpResponse

def index(request):
    return HttpResponse('PAGINA PARTIDO POLITICO')

def CambiarDatosCuentaP_view(request):
    return render(request, 'app/CambiarDatosCuentaP.html')

def CambioExitosoP_view(request):
    return render(request, 'app/CambioExitosoP.html')

def CrearPartidoPoliticoP_view(request):
<<<<<<< HEAD
    return render(request, 'app/CrearPartidoPoliticoP.html')
=======
    return render(request, 'app/CrearPartidoPoliticoP.html')

def ConsultarListaPartidosPoliticosAP_view(request):
    return render(request, 'app/ConsultarListaPartidosPoliticosAP.html')

def ConsultarListaPartidosPoliticosCP_view(request):
    return render(request, 'app/ConsultarListaPartidosPoliticosCP.html')

>>>>>>> 5176e908c0717b738d61ee472146b667e7d5d412

app/templates/app/CambiarDatosCuentaP.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cambiar datos de la cuenta</title>
    <link rel="stylesheet" href="{% static 'app/EstilosCambiarDatosCuentaP.css' %}">
    <!-- <link rel="stylesheet" href="EstilosV/Estilos4VA.css"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
</head>
<body>

    <div class="contenedor5">
        <div class="cuadro5">
            <div class="encabezado">
                <h1 class="registro">Cambiar datos de la cuenta</h1>
                <p>Ingrese en el campo el dato que desee cambiar</p>
                <!-- <a href="PaginaAdminVA.html">Regresar a la pagina de incio</a> -->
                <br>
            </div>

            <div class="datos1">
                <input type="text" id="nombre" placeholder="Nombres">
                <input type="text" id="apellidos" placeholder="Apellidos">
            </div>

            <br>

            <div class="datos2">
                <input type="text" id="usuario" placeholder="Ingrese su nuevo usuario">
                <input type="password" id="contraseña" placeholder="Ingrese su contraseña aquí">
            </div>

            <br>

            <div class="datos3">
                <input type="email" id="email" placeholder="Ingrese su e-mail aquí">
            </div>

            <br>

            <div class="boton1">
                <button><a href="{% url 'app:CambioExitosoP' %}">Cambiar</a></button>
            </div>
        </div>
        <div class="PiePagina">
            <img src="{% static 'app/IMAGEN2.png' %}" alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>
    </div>
    
</body>
</html>

app/templates/app/CambioExitosoP.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cultura Democrática</title>
    <link rel="stylesheet" href="{% static 'app/EstilosCambiarDatosCuentaP.css' %}">
    <!-- <link rel="stylesheet" href="EstilosV/Estilos4VA.css"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
</head>
<body>

    <div class="contenedor6">
        <div class="cuadro6">
            <br>
            <h1>Cambio exitoso</h1>
            <p>¡Sus datos datos han sido cambiados exitosamente!</p>
            <!-- <a href="PaginaAdminVA.html">Regresar a la página de incio</a> -->
            <!-- <a href="InicioVA.html">Cerrar sesión</a> -->
        </div>

        <div class="PiePagina">
            <img src="{% static 'app/IMAGEN2.png' %}" alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>
    </div>

</body>
</html>

app/templates/app/ConsultarListaPartidosPoliticosAP.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultar lista de partidos políticos</title>
    <link rel="stylesheet" href="{% static 'app/EstilosConsultarListaPartidosPoliticosP.css' %}">
    <!-- <link rel="stylesheet" href="Estilosp/estilosCListaPP.css"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="ConListaPP">
        <div class="BarraInicial">
            <i class="fas fa-search" id="logo1"></i>
            <span id="titulo">Consultar lista de partidos políticos</span>
        </div>
        <div class="Opciones">
            <i class="fas fa-search" id="logo2"></i>
            <span id="text1">¡ Ahora podrás ver toda la lista de partidos políticos ! "El conocimiento es poder"</span>
            <table border="1" id="tabla1">
                <thead>
                    <th>Nombre del partido político</th>
                    <th>Cantidad de visitas</th>
                    <th>Cantidad total de procesos</th>
                </thead>
                <tbody>
                    <tr>
                        <td id="td1">Partido ADA</td>
                        <td id="td2">23000 views</td>
                        <td id="td3">300</td>
                        
                    </tr>
                    <tr>
                        <td id="td4">Partido Colombia Renaciente</td>
                        <td id="td5">11000 views</td>
                        <td id="td6">200</td>
                        
                    </tr>
                    <tr>
                        <td id="td7">Partido Alianza Social Independiente ASI</td>
                        <td id="td8">20 views</td>
                        <td id="td9">100</td>
                        
                    </tr>
                    <tr>
                        <td id="td10">Partido Alianza Verde</td>
                        <td id="td11">23000 views</td>
                        <td id="td12">90</td>
                        
                    </tr>
                    <tr>
                        <td id="td13">Partido Cambio Radical</td>
                        <td id="td14">30000 views</td>
                        <td id="td15">80</td>
                        
                    </tr>
                    <tr>
                        <td id="td16">Partido Centro Democrático</td>
                        <td id="td17">3000 views</td>
                        <td id="td18">70</td>
                        
                    </tr>
                </tbody>
            </table>
            <span id="text2">Recuerda que toda la información presentada está totalmente VERIFICADA</span>
            <br>
            <i class="fas fa-user-check fa-10x" id="logo3"></i>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <!-- <a href="InicioVA.html" target="_blank" id="link1">Regresar a página de inicio</a> -->
            <!-- <a href="PaginaAdminVA.html" target="_blank" id="link2">Regresar a página de inicio de administrador</a> -->
        <div class="PiePagina">
            <img src="{% static 'app/IMAGEN2.png' %}" alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>
        </div>
    </div>
    
</body>
</html>

app/templates/app/ConsultarListaPartidosPoliticosCP.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultar lista de partidos políticos</title>
    <link rel="stylesheet" href="{% static 'app/EstilosConsultarListaPartidosPoliticosP.css' %}">
    <!-- <link rel="stylesheet" href="Estilosp/estilosCListaPP.css"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="ConListaPP">
        <div class="BarraInicial">
            <i class="fas fa-search" id="logo1"></i>
            <span id="titulo">Consultar lista de partidos políticos</span>
        </div>
        <div class="Opciones">
            <i class="fas fa-search" id="logo2"></i>
            <span id="text1">¡ Ahora podrás ver toda la lista de partidos políticos ! "El conocimiento es poder"</span>
            <table border="1" id="tabla1">
                <thead>
                    <th>Nombre del partido político</th>
                    <th>Cantidad de visitas</th>
                    <th>Cantidad total de procesos</th>
                </thead>
                <tbody>
                    <tr>
                        <td id="td1">Partido ADA</td>
                        <td id="td2">23000 views</td>
                        <td id="td3">300</td>
                        
                    </tr>
                    <tr>
                        <td id="td4">Partido Colombia Renaciente</td>
                        <td id="td5">11000 views</td>
                        <td id="td6">200</td>
                        
                    </tr>
                    <tr>
                        <td id="td7">Partido Alianza Social Independiente ASI</td>
                        <td id="td8">20 views</td>
                        <td id="td9">100</td>
                        
                    </tr>
                    <tr>
                        <td id="td10">Partido Alianza Verde</td>
                        <td id="td11">23000 views</td>
                        <td id="td12">90</td>
                        
                    </tr>
                    <tr>
                        <td id="td13">Partido Cambio Radical</td>
                        <td id="td14">30000 views</td>
                        <td id="td15">80</td>
                        
                    </tr>
                    <tr>
                        <td id="td16">Partido Centro Democrático</td>
                        <td id="td17">3000 views</td>
                        <td id="td18">70</td>
                        
                    </tr>
                </tbody>
            </table>
            <span id="text2">Recuerda que toda la información presentada está totalmente VERIFICADA</span>
            <br>
            <i class="fas fa-user-check fa-10x" id="logo3"></i>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <!-- <a href="InicioVA.html" target="_blank" id="link1">Regresar a página de inicio</a> -->
            <!-- <a href="PaginaCiuVA.html" target="_blank" id="link3">Regresar a página de inicio de ciudadano</a> -->
        </div>
        <div class="PiePagina">
            <img src="{% static 'app/IMAGEN2.png' %}" alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>
        </div>
    </div>
    
</body>
</html>

app/templates/app/ConsultarPartidoPoliticoSAR.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultar partidos políticos</title>
    <link rel="stylesheet" href="{% static 'app/estilosCPP.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>

<body>
    <div class="ConListaPP">
        
        <div class="BarraInicial">
            <i class="fas fa-search" id="logo1"></i>
            <span id="titulo">Consultar Partidos Políticos</span>
            
        </div>
        <div class="Opciones">
            <i class="fas fa-search" id="logo2"></i>
            <span id="text1"> ¡ Consulta ahora !</span>
            <div class="cuadro1">
                
               
                <p id="text2">Selecciona el nombre del partido político</p>
                <select name="Partido" id="ejemplo">
                    <option id="text3">Partido ADA</option>
                    <option id="text4">Partido Colombia Renaciente</option>
                    <option id="text5">Partido Alianza Social Independiente ASI</option>
                    <option id="text6">Partido Alianza Verde</option>
                    <option id="text7">Partido Cambio Radical</option>
                    <option id="text 8">Partido Centro Democrático</option>
                    <option id="text 9">Partido Colombia Justa Libres</option>
                    <option id="text 10">Partido Conservador Colombiano</option>
                    <option id="text 11">Partido FARC Fuerza Alternativa Revolucionaria del Común</option>
                    <option id="text 12">Partido Liberal Colombiano</option>
                    <option id="text 13">Partido Político MIRA</option>
                    <option id="text 14">Partido Polo Democrático Alternativo</option>
                    <option id="text 15">Partido Social de Unidad Nacional "Partido de la U"</option>
                    <option id="text 16">Movimiento Colombia Humana - Unión Patriótica UP</option>
                    <option id="text 17">Movimiento Autoridades Indígenas de Colombia AICO</option>
                    <option id="text 18">Movimiento Alternativo Indígena y Social MAIS</option>
                    
                </select>

            
                <br><button id="boton">CONSULTAR</button>



                   
                

            </div>

            <table border="1" id="tabla1" >
                <thead>
                    <tr>
                        
                        <!-- <th>Nombre partido político</th> -->
                        <!-- <th>Cantidad de visitas</th> -->
                       
                        <th colspan="2"></th>
                        <th colspan="2">Procesos</th>
                        <th colspan="4">Lista de afiliados</th>
                    </tr>
                    <tr>
                        <th scope="col">Nombre partido político</th>
                        <th scope="col">Cantidad de visitas</th>  
                        <th>Cantidad total de procesos</th>
                        <th>Cantidad total de procesos culpables</th>
                        <th>Apellidos</th>
                        <th>Nombres</th>
                        <th>Fecha de ingreso</th>
                        <th>Fecha de salida</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td id="td1">Partido ADA</td>
                        <td id="td2">100 views</td>
                        <td id="td3">30</td>
                        <th id="td4">23</th>
                        <th id="td5">Cardona Peralta</th>
                        <th id="td6">Juan Pablo</th>
                        <th id="td7">13/07/2019</th>
                        <th id="td8">20/05/2021</th>
                    </tr>
                    <tr>
                        <td id="td1">Partido Polo Democrático Alternativo</td>
                        <td id="td2">300 views</td>
                        <td id="td3">75</td>
                        <th id="td4">4</th>
                        <th id="td5">Castañeda Hernandez</th>
                        <th id="td6">Camilo Andrés</th>
                        <th id="td7">29/04/2015</th>
                        <th id="td8">13/05/2018</th>
                    </tr>
                    
                    
                </tbody>

            </table>
            <br>
            <a href="InicioVA.html" target="_blank" id="link1">Regresar a página de inicio</a>
            <a href="PaginaAdminVA.html" target="_blank" id="link2">Regresar a página de inicio de administrador</a>
            <a href="PaginaCiuVA.html" target="_blank" id="link3">Regresar a página de inicio de ciudadano</a>
        </div>
        <div class="PiePagina">
            <img src="{% static 'app/IMAGEN2.png' %}"  alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>

    </div>
   



    
</body>
</html>

app/templates/app/CrearPartidoPoliticoP.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear partido político</title>
    <link rel="stylesheet" href="{% static 'app/EstilosCrearPartidoPoliticoP.css' %}">
    <!-- <link rel="stylesheet" href="EstilosV/Estilos6VA.css"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
</head>
<body>

    <div class="contenedor8">
        <div class="cuadro8">
            <div class="encabezado">
                <h2>Crear partido político</h2>
                <p>Escriba en nombre del partido político que desea crear</p>
            </div>

            <div class="datos1">
                <p>Partido Político a crear:</p>
                <br>
                <input type="text" id="partido" placeholder="Ingrese el nombre del partido político">
                <br>
                <!-- <p>Nombre de creardor:</p>
                <br>
                <input type="text" id="nombre" placeholder="Ingrese el creador aquí"> -->
            </div>

            <div class="boton1">
                <!-- <button><a href="PaginaAdminVA.html">Enviar</a></button> -->
            </div>

        </div>


        <div class="PiePagina">
            <img src="{% static 'app/IMAGEN2.png' %}" alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>

    </div>
    
</body>
</html>

app/templates/app/ErrorInicioVA.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cultura Democrática</title>
    <link rel="stylesheet" href="EstilosV/estilosV.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
</head>
<body>

    <div class="contenedor2">
        <div class="cuadro2">
            <br>
            <h1>Ingreso Fallido</h1>
            <p>Sus datos son incorrectos verifique su usuario y su contraseña, por favor intente nuevamente</p>
            <a href="InicioVA.html">Regresar a la pagina de incio</a>
            <p>O también puedes registrarTe en el siguiente link</p>
            <a href="Registrarse.html">Registrarse en la página</a>
        </div>

        <div class="PiePagina">
            <img src="ImagenesP/IMAGEN2.png" alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>

    </div>
    
</body>
</html>

app/templates/app/InicioVA.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cultura Democrática</title>
    <link rel="stylesheet" href="EstilosV/estilosV.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">

</head>
<body>
    <div class="contenedor">
        <div class="intro">
            <h1>Cultura Democrática</h1>
            <p>Esta página permitirá tener una plataforma en linea para que los ciudadanos puedan hacer verificación de los casos Anticorrupción en Colombia</p>
            <p>¡Disfrutalo!</p>
        </div>

        <div class="Cuadro1">
            <div class="datos">
                <input type="text" name="Usuario" placeholder="Ingrese su usuario aquí">
                <br>
                <input type="password" name="Contraseña" placeholder="Ingrese su contraseña aquí">
                <br>
                <button><a href="PaginaCiuVA.html">Ingresar</a></button>
                <br>
                <button><a href="PaginaAdminVA.html">Inicio sesión Administrador</a></button>
                <br>
                <p>¿Deseas crear una cuenta? Registrate gratis</p>
                <a href="Registrarse.html">Crear una cuenta</a>
                <br>
                <a href="ErrorInicioVA.html">Error Inicio de sesión</a>
                
            </div>
        </div>

        <div class="PiePagina">
            <img src="ImagenesP/IMAGEN2.png" alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>
        
    </div>
</body>

</html>

app/templates/app/Registrarse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cultura Democrática</title>
    <link rel="stylesheet" href="EstilosV/Estilos2VA.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&display=swap" rel="stylesheet">
</head>
<body>

    <div class="contenedor3">
        <div class="cuadro3">
            <div class="encabezado">
                <h1 class="registro">Registrate en Cultura Democrática</h1>
                <p>¡Es totalmente gratis!</p>
                <p>Ingresando tus datos seras parte de Cultura Democrática</p>
                <a href="InicioVA.html">Regresar a la pagina de incio</a>
                <br>
            </div>

            <div class="datos1">
                <input type="text" id="nombre" placeholder="Nombres">
                <input type="text" id="apellidos" placeholder="Apellidos">
            </div>

            <br>

            <div class="datos2">
                <input type="text" id="usuario" placeholder="Ingrese su nuevo usuario">
                <input type="password" id="contraseña" placeholder="Ingrese su contraseña aquí">
            </div>

            <br>

            <div class="datos3">
                <input type="email" id="email" placeholder="Ingrese su e-mail aquí">
            </div>


            <div class="boton1">
                <p>Después de ingresar sus datos verfique su email e inicie sesión</p>
                <br>
                <button><a href="InicioVA.html">Enviar</a></button>
            </div>

        </div>

        <div class="PiePagina">
            <img src="ImagenesP/IMAGEN2.png" alt="IMAGEN REDES SOCIALES" id="imagen2">
        </div>
    </div>
    
</body>
</html>